import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import { cn } from './lib/utils'
import './globals.css'
import { Navbar } from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='en' className='light'>
			<body className={cn('min-h-screen antialiased', inter.className)}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
